Sprint 2/step 2
firstn1kon/cosmoburger pull request #3
Opened 2023-08-16 12:05 UTC by firstn1kon

final work sprint 2

2023-08-16 16:16 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошее понимание redux-toolkit
- Dnd настроен и работает отлично
- Использовали useMemo и useCallback

Необходимо исправить:
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.
- Открытие модального окна ингредиента так же должно управляться через `redux`. Т.е. должны быть создано хранилище с текущим просматриваемым ингредиентом. 

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-16 16:16 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const {isLoading, isError, isIngredientModalOpen} = useSelector(state => state.ingredients)
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-08-16 16:16 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredient/view-ingredient/view-ingredient.jsx
> +    const countIngredient = createSelector(
**Можно лучше**
Селекторы лучше выносить в отдельный файл с селекторами, чтобы не загружать файл

2023-08-16 16:16 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        }
**Можно лучше**
Модалка с `IngredientDetails ` больше относится к `BurgerIngredients ` нежели к App. Лучше перенести туда

2023-08-16 16:16 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <Tab value="bun" active={tab === 'bun'} onClick={() => moveToPosition(0)}>Булки</Tab>
**Можно лучше**
Тут можно передавать не анонимную функцию, а сразу `moveToPosition `. onClick передает в колбек `value`. Нужно использовать его вместо `index`

2023-08-16 18:59 UTC, firstn1kon commented
Не могли бы вы пояснить более конкретно по пунктам ниже, чтобы я  правильно все поправил 
> Необходимо исправить:
> 
> * Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов

Пока мы делаем два запроса к API - это получение ингредиентов и отправка заказа. Если произойдет ошибка, то в соответствующий  стейт будет записано **isError = error.message**. Если ошибка произошла при загрузке ингредиентов, то отрендериться компонент `<Error err={isError} reload={true}/>` (модалка) в нем будет отображаться **error.message**, при закрытие модалки пойдет повторный запрос (просто reload). Так как эта ошибка может произойти только при первоначальном открытие приложения (запрос делается при монтирование компонента) то стейт и так будет изначальным, за исключением isError, но когда мы закроем модалку   isError вернется в первоначальное состояние. (false)

Если ошибка произошла при отправке заказа, тоже будет компонент `<Error err={isError} tryAgain={tryAgain}/>`  в нем будет отображаться **error.message** и при закрытие этой модалки order-slice будет приводиться к initialState и номера заказа там не будет.
Я не совсем понимаю, как еще надо обработать ошибки. На данный момент пользователю показывается модалка с ошибкой и при ее закрытие все стейты возращаются в initialState

> * Открытие модального окна ингредиента так же должно управляться через `redux`. Т.е. должны быть создано хранилище с текущим просматриваемым ингредиентом.
> 
Именно так и сделано `const initialState = {
    ingredients: [],
    isLoading: false,
    isError: false,
     вот тут => viewIngredient: null,
    вот тут => isIngredientModalOpen: false,
    currentTab: "bun"
}`
Эта сущность относится к ингредиентам и находится в слайсе ingredients-slice.js

2023-08-16 19:01 UTC, firstn1kon commented on src/components/app/app.jsx
> +  const {isLoading, isError, isIngredientModalOpen} = useSelector(state => state.ingredients)
Спасибо, все очень доходчиво. Сделаю рефакторинг

2023-08-16 19:08 UTC, firstn1kon commented on src/components/burger-ingredients/ingredient/view-ingredient/view-ingredient.jsx
> +    const countIngredient = createSelector(
Здесь createSelector используется немного нестандартно, если я его вынесу в отдельный файл, то будет ошибка, т.к. не будет доступа к data._id и data.type. Можно было бы получать данные из стейта, далее создать функцию (обернуть ее в useCallback) и там уже обрабатывать, но т.к. createSelector внутри уже содержит механизм мемомизации, и кода будет меньше, принял решение использовать его так.

2023-08-16 19:08 UTC, firstn1kon commented on src/components/app/app.jsx
> +        }
Согласен, перенесу

2023-08-16 19:09 UTC, firstn1kon commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <Tab value="bun" active={tab === 'bun'} onClick={() => moveToPosition(0)}>Булки</Tab>
Сразу не сообразил :) Да, конечно, так будет лучше, сделаю рефакторинг

2023-08-17 16:43 UTC, andryxxa93 commented
> Не могли бы вы пояснить более конкретно по пунктам ниже, чтобы я правильно все поправил
> 
> > Необходимо исправить:
> > 
> > * Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов
> 
> Пока мы делаем два запроса к API - это получение ингредиентов и отправка заказа. Если произойдет ошибка, то в соответствующий стейт будет записано **isError = error.message**. Если ошибка произошла при загрузке ингредиентов, то отрендериться компонент `<Error err={isError} reload={true}/>` (модалка) в нем будет отображаться **error.message**, при закрытие модалки пойдет повторный запрос (просто reload). Так как эта ошибка может произойти только при первоначальном открытие приложения (запрос делается при монтирование компонента) то стейт и так будет изначальным, за исключением isError, но когда мы закроем модалку isError вернется в первоначальное состояние. (false)
> 
> Если ошибка произошла при отправке заказа, тоже будет компонент `<Error err={isError} tryAgain={tryAgain}/>` в нем будет отображаться **error.message** и при закрытие этой модалки order-slice будет приводиться к initialState и номера заказа там не будет. Я не совсем понимаю, как еще надо обработать ошибки. На данный момент пользователю показывается модалка с ошибкой и при ее закрытие все стейты возращаются в initialState
> 
> > * Открытие модального окна ингредиента так же должно управляться через `redux`. Т.е. должны быть создано хранилище с текущим просматриваемым ингредиентом.
> 
> Именно так и сделано `const initialState = { ingredients: [], isLoading: false, isError: false, вот тут => viewIngredient: null, вот тут => isIngredientModalOpen: false, currentTab: "bun" }` Эта сущность относится к ингредиентам и находится в слайсе ingredients-slice.js

- Прощу прощения, эту логику я не считал в коде. Такая логика решает проблему.

2023-08-17 17:01 UTC, andryxxa93 commented
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-17 17:12 UTC, merged